import { State, Device, Service, Characteristic, ScanOptions, ConnectionOptions, Subscription } from './types';
type DeviceListener = (error: Error | null, device: Device | null) => void;
type CharacteristicListener = (error: Error | null, characteristic: Characteristic | null) => void;
type StateChangeListener = (state: State) => void;
export declare class BleProxyManager {
    private client;
    private initialized;
    private scanListener;
    private scanEventHandler;
    private monitorListeners;
    private connectedDevices;
    private deviceCache;
    private stateListeners;
    private currentState;
    constructor();
    state(): Promise<State>;
    onStateChange(listener: StateChangeListener, emitCurrentState?: boolean): Subscription;
    startDeviceScan(UUIDs: string[] | null, options: ScanOptions | null, listener: DeviceListener): void;
    stopDeviceScan(): void;
    connectToDevice(deviceId: string, options?: ConnectionOptions): Promise<Device>;
    cancelDeviceConnection(deviceId: string): Promise<Device>;
    isDeviceConnected(deviceId: string): Promise<boolean>;
    discoverAllServicesAndCharacteristicsForDevice(deviceId: string): Promise<Device>;
    servicesForDevice(deviceId: string): Promise<Service[]>;
    characteristicsForDevice(deviceId: string, serviceUUID: string): Promise<Characteristic[]>;
    readCharacteristicForDevice(deviceId: string, serviceUUID: string, characteristicUUID: string): Promise<Characteristic>;
    writeCharacteristicWithResponseForDevice(deviceId: string, serviceUUID: string, characteristicUUID: string, valueBase64: string): Promise<Characteristic>;
    writeCharacteristicWithoutResponseForDevice(deviceId: string, serviceUUID: string, characteristicUUID: string, valueBase64: string): Promise<Characteristic>;
    monitorCharacteristicForDevice(deviceId: string, serviceUUID: string, characteristicUUID: string, listener: CharacteristicListener): Subscription;
    readRSSIForDevice(deviceId: string): Promise<Device>;
    destroy(): void;
    private ensureInitialized;
    private writeCharacteristic;
    private convertManagerState;
    private convertDevice;
    private convertServiceData;
    private convertService;
    private convertCharacteristic;
    private convertOptionsToStrings;
}
export {};
